project_id = "pakwuooxumrghsbwczwx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.identify-animal]
    verify_jwt = false
  [functions.search-users]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-reengagement]
    verify_jwt = true
  [functions.notify-friend-request]
    verify_jwt = false
  [functions.public-stats]
    verify_jwt = false
